import type { Metadata } from "next";
import "./globals.css";
import { Provider } from "@/app/provider";
import Sidemenu from "@/components/ui/sidemenu"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Sidemenu/>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
