import type { Metadata } from "next";
import "./globals.css";
import { Provider } from "@/app/provider";
import Sidemenu from "@/components/ui/sidemenu"
import Navbar from "@/components/ui/navbar";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >

          {/* <div className=""> */}
            <Navbar />
        <div className=" flex w-full">
        <Sidemenu />
          <Provider>{children}</Provider>
        </div>
          {/* </div> */}
      </body>
    </html>
  );
}
